//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cevreSehircilik.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cevreSehircilikEntities : DbContext
    {
        public cevreSehircilikEntities()
            : base("name=cevreSehircilikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblHakkimizda> tblHakkimizda { get; set; }
        public virtual DbSet<tbliletisim> tbliletisim { get; set; }
        public virtual DbSet<tblKategori> tblKategori { get; set; }
        public virtual DbSet<tblsehir> tblsehir { get; set; }
        public virtual DbSet<tblTur> tblTur { get; set; }
        public virtual DbSet<tblYorum> tblYorum { get; set; }
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
    }
}
